# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orchestrator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'orchestrator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12orchestrator.proto\x12\x11orchestrator_grpc\",\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\xce\x01\n\x10\x41gentTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x14\n\x0crequester_id\x18\x02 \x01(\t\x12\x11\n\ttask_type\x18\x03 \x01(\t\x12\x30\n\x08messages\x18\x04 \x03(\x0b\x32\x1e.orchestrator_grpc.ChatMessage\x12\x10\n\x08priority\x18\x05 \x01(\x05\x12\x12\n\ntimeout_ms\x18\x06 \x01(\x05\x12\x18\n\x10requires_context\x18\x07 \x01(\x08\x12\x0e\n\x06stream\x18\x08 \x01(\x08\"\xcf\x01\n\x11\x41gentTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x10\n\x08is_final\x18\x04 \x01(\x08\x12\x15\n\rprompt_tokens\x18\x05 \x01(\x05\x12\x19\n\x11\x63ompletion_tokens\x18\x06 \x01(\x05\x12\x1a\n\x12processing_time_ms\x18\x07 \x01(\x05\x12\x0f\n\x07success\x18\x08 \x01(\x08\x12\x15\n\rerror_message\x18\t \x01(\t\"c\n\x10HeartbeatRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\x12\x15\n\rcurrent_slots\x18\x03 \x01(\x05\x12\x17\n\x0fmemory_usage_mb\x18\x04 \x01(\x05\":\n\x11HeartbeatResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\xa6\x02\n\x18OrchestratorAgentService\x12W\n\nSubmitTask\x12#.orchestrator_grpc.AgentTaskRequest\x1a$.orchestrator_grpc.AgentTaskResponse\x12Y\n\nStreamTask\x12#.orchestrator_grpc.AgentTaskRequest\x1a$.orchestrator_grpc.AgentTaskResponse0\x01\x12V\n\tHeartbeat\x12#.orchestrator_grpc.HeartbeatRequest\x1a$.orchestrator_grpc.HeartbeatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orchestrator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATMESSAGE']._serialized_start=41
  _globals['_CHATMESSAGE']._serialized_end=85
  _globals['_AGENTTASKREQUEST']._serialized_start=88
  _globals['_AGENTTASKREQUEST']._serialized_end=294
  _globals['_AGENTTASKRESPONSE']._serialized_start=297
  _globals['_AGENTTASKRESPONSE']._serialized_end=504
  _globals['_HEARTBEATREQUEST']._serialized_start=506
  _globals['_HEARTBEATREQUEST']._serialized_end=605
  _globals['_HEARTBEATRESPONSE']._serialized_start=607
  _globals['_HEARTBEATRESPONSE']._serialized_end=665
  _globals['_EMPTY']._serialized_start=667
  _globals['_EMPTY']._serialized_end=674
  _globals['_ORCHESTRATORAGENTSERVICE']._serialized_start=677
  _globals['_ORCHESTRATORAGENTSERVICE']._serialized_end=971
# @@protoc_insertion_point(module_scope)
