# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import orchestrator_pb2 as orchestrator__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in orchestrator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrchestratorAgentServiceStub(object):
    """─── Services ───────────────────────────────────────────────────────────────

    Agent ↔ Orchestrator (internal)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitTask = channel.unary_unary(
                '/orchestrator_grpc.OrchestratorAgentService/SubmitTask',
                request_serializer=orchestrator__pb2.AgentTaskRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.AgentTaskResponse.FromString,
                _registered_method=True)
        self.StreamTask = channel.unary_stream(
                '/orchestrator_grpc.OrchestratorAgentService/StreamTask',
                request_serializer=orchestrator__pb2.AgentTaskRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.AgentTaskResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/orchestrator_grpc.OrchestratorAgentService/Heartbeat',
                request_serializer=orchestrator__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class OrchestratorAgentServiceServicer(object):
    """─── Services ───────────────────────────────────────────────────────────────

    Agent ↔ Orchestrator (internal)
    """

    def SubmitTask(self, request, context):
        """Unary task submission
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTask(self, request, context):
        """Server-streaming task submission
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorAgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=orchestrator__pb2.AgentTaskRequest.FromString,
                    response_serializer=orchestrator__pb2.AgentTaskResponse.SerializeToString,
            ),
            'StreamTask': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTask,
                    request_deserializer=orchestrator__pb2.AgentTaskRequest.FromString,
                    response_serializer=orchestrator__pb2.AgentTaskResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=orchestrator__pb2.HeartbeatRequest.FromString,
                    response_serializer=orchestrator__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orchestrator_grpc.OrchestratorAgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orchestrator_grpc.OrchestratorAgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrchestratorAgentService(object):
    """─── Services ───────────────────────────────────────────────────────────────

    Agent ↔ Orchestrator (internal)
    """

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator_grpc.OrchestratorAgentService/SubmitTask',
            orchestrator__pb2.AgentTaskRequest.SerializeToString,
            orchestrator__pb2.AgentTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/orchestrator_grpc.OrchestratorAgentService/StreamTask',
            orchestrator__pb2.AgentTaskRequest.SerializeToString,
            orchestrator__pb2.AgentTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator_grpc.OrchestratorAgentService/Heartbeat',
            orchestrator__pb2.HeartbeatRequest.SerializeToString,
            orchestrator__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ClientOrchestratorServiceStub(object):
    """Client ↔ Orchestrator (external)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_unary(
                '/orchestrator_grpc.ClientOrchestratorService/Chat',
                request_serializer=orchestrator__pb2.ClientChatRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.ClientChatResponse.FromString,
                _registered_method=True)
        self.StreamChat = channel.unary_stream(
                '/orchestrator_grpc.ClientOrchestratorService/StreamChat',
                request_serializer=orchestrator__pb2.ClientChatRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.ClientChatResponse.FromString,
                _registered_method=True)


class ClientOrchestratorServiceServicer(object):
    """Client ↔ Orchestrator (external)
    """

    def Chat(self, request, context):
        """Unary chat completion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamChat(self, request, context):
        """Server-streaming chat completion (token-by-token)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientOrchestratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=orchestrator__pb2.ClientChatRequest.FromString,
                    response_serializer=orchestrator__pb2.ClientChatResponse.SerializeToString,
            ),
            'StreamChat': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamChat,
                    request_deserializer=orchestrator__pb2.ClientChatRequest.FromString,
                    response_serializer=orchestrator__pb2.ClientChatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orchestrator_grpc.ClientOrchestratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orchestrator_grpc.ClientOrchestratorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientOrchestratorService(object):
    """Client ↔ Orchestrator (external)
    """

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator_grpc.ClientOrchestratorService/Chat',
            orchestrator__pb2.ClientChatRequest.SerializeToString,
            orchestrator__pb2.ClientChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/orchestrator_grpc.ClientOrchestratorService/StreamChat',
            orchestrator__pb2.ClientChatRequest.SerializeToString,
            orchestrator__pb2.ClientChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
